#!/usr/bin/env python3
"""Spec-004 resume customization agent — staged orchestrator.

Pipeline: S0 extract -> S1 plan (LLM) -> S2 verify-plan (script, 1 retry)
-> S3 draft (LLM) -> S4 QA gates (scripts + bounded repairs) -> CL cover
letter -> evaluation.md. Human checkpoints CP1 (plan) and CP2 (final PDFs)
are enforced via --approve-plan / interactive prompt unless --yes.

Usage:
  python3 -m scripts.resume_agent.run --jd-file <path> [--company X] [--title Y]
  python3 -m scripts.resume_agent.run --url https://...
  python3 -m scripts.resume_agent.run --text-file pasted.txt
  python3 -m scripts.resume_agent.run --resume-existing <app_dir>   # letter only
"""
from __future__ import annotations

import argparse
import datetime
import json
import re
import sys
from pathlib import Path

from .common import (APPLICATIONS_DIR, BASE_VARIANTS, BULLET_PATTERNS_MD,
                     EVIDENCE_MD, FAMILY_KEYWORDS, FAMILY_TEMPLATE,
                     JD_ACTIVE_DIR, KEYWORD_BANK_MD, ROLE_FAMILIES_MD,
                     ats_roundtrip, check_page_count, cl_gate, compile_tex,
                     extract_json_object, factuality_gate,
                     llm_chat, log, number_audit, orphan_lines,
                     render_letter_tex, sanitize_tex, slugify)
from . import prompts
from .verify_plan import page_target_for, verify_plan

MAX_PLAN_RETRIES = 2
MAX_GATE_REPAIRS = 2


# ---------------------------------------------------------------------------
# S0 — load JD (reuses tailor_from_jd fetchers via subprocess-free import)
# ---------------------------------------------------------------------------

def load_jd(args) -> dict:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from scripts.tailor_from_jd import fetch_jd_from_url, parse_jd_text

    if args.url:
        jd = fetch_jd_from_url(args.url)
    elif args.jd_file:
        jd = parse_jd_text(Path(args.jd_file).read_text(errors="replace"))
    else:
        jd = parse_jd_text(Path(args.text_file).read_text(errors="replace"))
    if args.company:
        jd["company"] = args.company
    if args.title:
        jd["title"] = args.title
    if not jd.get("description") or len(jd["description"]) < 400:
        raise RuntimeError("JD text too short/missing — paste the full description")
    return jd


def quick_family(jd_text: str) -> tuple[str, dict]:
    low = jd_text.lower()
    scores = {fam: sum(1 for k in kws if k in low)
              for fam, kws in FAMILY_KEYWORDS.items()}
    ranked = sorted(scores.items(), key=lambda kv: -kv[1])
    top = ranked[0]
    return (top[0] if top[1] > 0 else "research_engineer_agentic"), scores


def recent_plans(days: int = 30) -> list[dict]:
    out = []
    cutoff = datetime.date.today() - datetime.timedelta(days=days)
    for d in APPLICATIONS_DIR.glob("*_20*"):
        m = re.search(r"_(\d{8})$", d.name)
        if not m:
            continue
        try:
            tag = datetime.datetime.strptime(m.group(1), "%Y%m%d").date()
        except ValueError:
            continue
        pj = d / "plan.json"
        if tag >= cutoff and pj.exists():
            try:
                p = json.loads(pj.read_text())
                out.append({"slug": d.name,
                            "blocks": [b.get("block", b) if isinstance(b, dict)
                                       else b for b in p.get("featured_blocks", [])]})
            except Exception:  # noqa: BLE001
                continue
    return out


def select_evidence(plan: dict, evidence_md: str) -> str:
    """Extract full text of featured blocks from the library."""
    from ._blocks import iter_blocks

    wanted = {(fb.get("block") or "").strip().lower()
              for fb in plan["featured_blocks"]}
    parts = [raw.rstrip() for title, raw in iter_blocks(evidence_md)
             if title in wanted]
    return "\n\n".join(parts)


def strip_tagline_candidates(tex: str) -> tuple[str, list[str]]:
    cands = re.findall(r"% TAGLINE-CANDIDATE: (.+)", tex)
    return tex, cands


def write_evaluation(app_dir: Path, jd: dict, plan: dict, family: str,
                     pages: int, target: int, gate_iters: int,
                     cl_words: int, qa_notes: list[str]) -> None:
    date_tag = app_dir.name.rsplit("_", 1)[-1]
    dispositions = "\n".join(
        f"| {kd.get('term','')} | {kd.get('tier','')} | {kd.get('disposition','')} "
        f"| {kd.get('evidence_block','')} |"
        for kd in plan.get("keyword_dispositions", []))
    md = f"""# Evaluation — {jd['company']} · {jd['title']} ({date_tag})

**Generated by:** `scripts/resume_agent/run.py` (spec 004 staged agent)
**Diagnosed family:** `{family}` · seniority: {plan.get('seniority', 'n/a')}
**Chosen narrative:** {plan.get('chosen_narrative', '')}
**Rejected alternative:** {plan.get('alternative_narrative', '')}

## Requirement map
- **P0:** {'; '.join(p.get('requirement', p) if isinstance(p, dict) else p for p in plan.get('p0', [])) or '(none)'}
- **P1:** {'; '.join(plan.get('p1', []))}
- **P2:** {'; '.join(plan.get('p2', []))}

## Featured blocks
{chr(10).join(f"- **{b.get('block')}** → {b.get('target_section')}: covers {b.get('why')}" for b in plan.get('featured_blocks', []))}

## Omitted blocks (recorded, never filled)
{chr(10).join(f"- {o.get('block')}: {o.get('reason')}" for o in plan.get('omitted_blocks', [])) or '- none'}

## Keyword dispositions
| Term | Tier | Disposition | Evidence block |
|---|---|---|---|
{dispositions}

## QA gates
- Factuality grep: PASS after {gate_iters} repair iteration(s)
- Page count: {pages} (target {target})
- ATS round-trip + orphan detector: see run log
{chr(10).join(f'- {n}' for n in qa_notes)}

## Cover letter
- Word count: {cl_words} (limit 250); banned-term gate PASS

## Review checklist (before submission)
- [ ] CP2 human review of rendered resume.pdf + cover_letter.pdf
"""
    (app_dir / "evaluation.md").write_text(md)


def run(args) -> int:
    started = __import__("time").time()

    # ---- S0 -----------------------------------------------------------
    jd = load_jd(args)
    jd_text = jd["description"]
    digest = __import__("hashlib").sha256(jd_text.encode()).hexdigest()
    job_slug = f"{slugify(jd['company'])}_{slugify(jd['title'])}"[:110]
    date_tag = datetime.date.today().strftime("%Y%m%d")
    app_dir = APPLICATIONS_DIR / f"{job_slug}_{date_tag}"
    app_dir.mkdir(parents=True, exist_ok=True)
    jd_path = JD_ACTIVE_DIR / f"{job_slug}_manual_{digest[:8]}.md"
    JD_ACTIVE_DIR.mkdir(parents=True, exist_ok=True)
    if not jd_path.exists():
        jd_path.write_text(
            f"# {jd['title']} — {jd['company']}\n\n- Source: manual_upload\n"
            f"- URL: {jd.get('source_url') or '(none)'}\n- Hash (sha256): {digest}\n"
            f"- Discovered: {datetime.date.today().isoformat()}\n\n"
            f"## Full Job Description Text\n{jd_text}\n\n---\n")
    (app_dir / "jd.json").write_text(json.dumps(jd, indent=2))
    log(f"S0 ok: {jd['title']} @ {jd['company']} -> {app_dir}")

    evidence_md = EVIDENCE_MD.read_text()
    families_md = ROLE_FAMILIES_MD.read_text()
    bullet_rules = BULLET_PATTERNS_MD.read_text()
    keyword_bank = KEYWORD_BANK_MD.read_text() if KEYWORD_BANK_MD.exists() else ""

    # ---- S1 plan --------------------------------------------------------
    fam_guess, _ = quick_family(jd_text)

    if getattr(args, "reuse_plan", False) and (app_dir / "plan.json").exists():
        plan = json.loads((app_dir / "plan.json").read_text())
        plan_errors = verify_plan(plan, evidence_md, jd_text)
        if plan_errors:
            raise RuntimeError("--reuse-plan: existing plan invalid:\n" +
                               "\n".join(plan_errors))
        log("S1/S2 skipped (--reuse-plan): loaded existing validated plan")
    else:
        plan_errors = []
        plan = {}
        for attempt in range(1 + MAX_PLAN_RETRIES):
            sys_p, usr_p = prompts.plan_prompt(
                jd_text, fam_guess, families_md,
                prompts.evidence_index(evidence_md), keyword_bank,
                recent_plans() if attempt == 0 else [])
            if plan_errors:
                usr_p += ("\n\nYOUR PREVIOUS PLAN FAILED VALIDATION. Fix exactly "
                          "these errors:\n" + "\n".join(f"- {e}" for e in plan_errors))
            reply = llm_chat([{"role": "system", "content": sys_p},
                              {"role": "user", "content": usr_p}], temperature=0.2)
            try:
                candidate = extract_json_object(reply)
            except ValueError as exc:
                plan_errors = [f"JSON unparseable: {exc}"]
                continue
            plan_errors = verify_plan(candidate, evidence_md, jd_text)
            if not plan_errors:
                plan = candidate
                break
        if plan_errors:
            raise RuntimeError("plan validation failed after retries:\n" +
                               "\n".join(plan_errors))
        (app_dir / "plan.json").write_text(json.dumps(plan, indent=2))
    family = plan["family"]
    target = page_target_for(plan)
    log(f"S1/S2 ok: family={family} blocks="
        f"{[b.get('block') for b in plan['featured_blocks']]}")

    # ---- CP1 human checkpoint ------------------------------------------
    if not args.yes:
        ans = input(f"\nCP1 — approve plan? family={family}, "
                    f"blocks={[b.get('block') for b in plan['featured_blocks']]}, "
                    f"target={target}p [y/N/edit-path] ")
        if ans.strip().lower() not in ("y", "yes"):
            log("CP1 not approved — plan saved; review plan.json and re-run with "
                "--resume-existing")
            return 2

    selected_ev = select_evidence(plan, evidence_md)
    (app_dir / "selected_evidence.md").write_text(selected_ev)

    # ---- S3 draft -------------------------------------------------------
    base_stem = FAMILY_TEMPLATE[family]
    base_tex = (BASE_VARIANTS / f"{base_stem}.tex").read_text()
    sys_d, usr_d = prompts.draft_prompt(base_tex, selected_ev, plan, jd_text,
                                        bullet_rules, target)
    tex_raw = llm_chat([{"role": "system", "content": sys_d},
                        {"role": "user", "content": usr_d}],
                       temperature=0.3, max_tokens=8000)
    tex_raw = re.sub(r"^```(?:latex|tex)?\n?", "", tex_raw.strip())
    tex_raw = tex_raw.rstrip("`").strip()
    if r"\begin{document}" not in tex_raw:
        raise RuntimeError("drafter did not return a complete LaTeX document")
    tex_raw, sanitize_fixes = sanitize_tex(tex_raw)
    if sanitize_fixes:
        log(f"sanitizer: {len(sanitize_fixes)} bare-% escapes applied")

    # ---- S4 gates ---------------------------------------------------------
    gate_iters = 0
    violations = factuality_gate(tex_raw)
    while violations and gate_iters < MAX_GATE_REPAIRS:
        gate_iters += 1
        log(f"factuality repair {gate_iters}: {violations[:3]}")
        sys_r, usr_r = prompts.repair_prompt(violations, tex_raw)
        fixed = llm_chat([{"role": "system", "content": sys_r},
                          {"role": "user", "content": usr_r}],
                         temperature=0.2, max_tokens=8000)
        tex_raw = re.sub(r"^```(?:latex|tex)?\n?", "", fixed.strip())
        tex_raw = tex_raw.rstrip("`").strip()
        tex_raw, more = sanitize_tex(tex_raw)
        violations = factuality_gate(tex_raw)
    if violations:
        raise RuntimeError("factuality gate still failing:\n" + "\n".join(violations))

    resume_tex = app_dir / "resume.tex"

    def try_compile(src: str) -> tuple[Path | None, list[str]]:
        resume_tex.write_text(src)
        try:
            return (*compile_tex(resume_tex, app_dir),)
        except RuntimeError as exc:
            log(f"compile failed: {str(exc)[:200]}")
            return None, []

    pdf, warnings = try_compile(tex_raw)

    # Compile-repair loop (observed failure mode: drafter emits structurally
    # broken LaTeX). Bounce the exact pdflatex error back to the model.
    compile_rounds = 0
    while pdf is None and compile_rounds < MAX_GATE_REPAIRS:
        compile_rounds += 1
        err_tail = (app_dir / "resume.log").read_text(errors="replace")[-1500:]
        log(f"compile repair round {compile_rounds}")
        fixed = llm_chat(
            [{"role": "system",
              "content": "You fix LaTeX compile errors in resumes. Return only "
                         "the corrected complete .tex that compiles with "
                         "pdflatex. Change nothing else."},
             {"role": "user",
              "content": f"This resume.tex fails to compile:\n\n{err_tail}\n\n"
                         f"Fix ONLY the structural/escaping error. Return full .tex.\n\n{tex_raw}"}],
            temperature=0.2, max_tokens=8000)
        cand = re.sub(r"^```(?:latex|tex)?\n?", "", fixed.strip()).rstrip("`")
        if r"\begin{document}" not in cand or factuality_gate(cand):
            log("compile repair rejected (incomplete or banned terms)")
            continue
        cand, _ = sanitize_tex(cand)
        new_pdf, new_warn = try_compile(cand)
        if new_pdf is not None:
            tex_raw, pdf, warnings = cand, new_pdf, new_warn
    if pdf is None:
        raise RuntimeError("resume failed to compile after repair rounds")

    pages = check_page_count(pdf)

    # Page-fit ladder (spec §6): trim via drafter until within target.
    fit_rounds = 0
    while pages > target and fit_rounds < MAX_GATE_REPAIRS:
        fit_rounds += 1
        log(f"page-fit trim round {fit_rounds}: {pages}p > target {target}p")
        trimmed = llm_chat(
            [{"role": "system", "content": prompts.REPAIR_SYSTEM},
             {"role": "user", "content": prompts.PAGE_FIT_PROMPT_TRIM.format(
                 pages=pages, target=target, tex=tex_raw)}],
            temperature=0.2, max_tokens=8000)
        cand = re.sub(r"^```(?:latex|tex)?\n?", "", trimmed.strip()).rstrip("`")
        if r"\begin{document}" not in cand or factuality_gate(cand):
            log("trim rejected (incomplete or new violations)")
            continue
        cand_tex = app_dir / "resume.tex"
        cand_tex.write_text(cand)
        try:
            cand_pdf, _ = compile_tex(cand_tex, app_dir)
            cand_pages = check_page_count(cand_pdf)
        except RuntimeError as exc:
            log(f"trim failed to compile: {exc}")
            continue
        if cand_pages <= pages:
            tex_raw, pdf, pages = cand, cand_pdf, cand_pages
        if pages <= target:
            break

    # Orphan + number audits + ATS round-trip.
    orphans = orphan_lines(pdf)
    nums = number_audit(tex_raw, selected_ev + "\n" + base_tex)
    ats = ats_roundtrip(pdf, plan)
    qa_notes = ([f"Orphan lines remaining (review): {len(orphans)}"] +
                ([f"Unverifiable numerals: {nums[:5]}"] if nums else []) +
                [f"ATS round-trip issues: {ats}" if ats else "ATS round-trip: PASS"])

    # ---- Cover letter ----------------------------------------------------
    top_p0s = plan["p0"][:3]
    research = ""
    rp = app_dir / "research.md"
    if rp.exists():
        research = rp.read_text()
    sys_c, usr_c = prompts.cover_letter_prompt(
        jd_text, jd["company"], jd["title"], top_p0s,
        selected_ev[:6000], research or None)
    cl_text = llm_chat([{"role": "system", "content": sys_c},
                        {"role": "user", "content": usr_c}], temperature=0.5)
    cl_bad = cl_gate(cl_text)
    if cl_bad:
        cl_text = llm_chat(
            [{"role": "system",
              "content": "You remove banned terminology from cover letters, "
                         "preserving meaning. Return only the corrected letter."},
             {"role": "user", "content": prompts.CL_REPAIR_PROMPT.format(
                 bad=", ".join(cl_bad), text=cl_text)}], temperature=0.3)
        cl_bad = cl_gate(cl_text)
        if cl_bad:
            raise RuntimeError(f"cover letter banned terms remain: {cl_bad}")
    words = len(cl_text.split())
    cl_tex = app_dir / "cover_letter.tex"
    cl_tex.write_text(render_letter_tex(jd["title"], jd["company"], cl_text))
    cl_pdf, _ = compile_tex(cl_tex, app_dir)

    write_evaluation(app_dir, jd, plan, family, pages, target, gate_iters,
                     words, qa_notes)

    print(f"""
=== SPEC-004 AGENT PACKAGE ===
job      : {jd['title']} @ {jd['company']}
family   : {family} ({', '.join(b.get('block','') for b in plan['featured_blocks'])})
output   : {app_dir}
resume   : {pdf.name} ({pages}p / target {target}p; {len(warnings)} box warnings)
orphans  : {len(orphans)}; nums-unverified: {len(nums)}; ATS: {'FAIL' if ats else 'PASS'}
letter   : {cl_pdf.name} ({words} words)
elapsed  : {__import__('time').time()-started:.0f}s
STATUS   : CP2 PENDING — human review of PDFs before submission
""")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--jd-file")
    src.add_argument("--url")
    src.add_argument("--text-file")
    src.add_argument("--spec-file", help="UI spec JSON {url|text|file, company, title}")
    ap.add_argument("--company")
    ap.add_argument("--title")
    ap.add_argument("--yes", action="store_true", help="auto-approve CP1")
    ap.add_argument("--reuse-plan", action="store_true",
                    help="skip S1/S2: load plan.json from a previous run in "
                         "the same app dir (saves an LLM round)")
    args = ap.parse_args(argv)
    if args.spec_file:
        spec = json.loads(Path(args.spec_file).read_text())
        args.url = spec.get("url")
        if spec.get("text"):
            tmp = Path(args.spec_file).parent / "jd_text.txt"
            tmp.write_text(spec["text"])
            args.text_file = str(tmp)
        elif spec.get("file"):
            args.jd_file = spec["file"]
        args.company = args.company or spec.get("company")
        args.title = args.title or spec.get("title")
    try:
        return run(args)
    except Exception as exc:  # noqa: BLE001
        log(f"FATAL: {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
